# Generated by Django 3.1.5 on 2021-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('confirmed', models.CharField(max_length=100)),
                ('deceased', models.CharField(max_length=100)),
                ('recovered', models.CharField(max_length=100)),
            ],
        ),
    ]
