# Generated by Django 3.1.5 on 2021-05-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidcases',
            old_name='district',
            new_name='district_name',
        ),
    ]
