# Generated by Django 3.1.5 on 2021-05-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210503_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidcases',
            old_name='district_name',
            new_name='district',
        ),
    ]
