# Generated by Django 3.1.5 on 2021-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210503_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
                ('confirmed', models.IntegerField()),
                ('deceased', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CovidCases',
        ),
    ]
