# Generated by Django 3.1.5 on 2021-06-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210518_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddistrict',
            name='published_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
